services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: physiomobile-app
    volumes:
      - .:/var/www/html
    ports:
      - "9009:9000"
    networks:
      - physiomobile
    env_file:
      - .env
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: physiomobile-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: physiomobile
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dev
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - physiomobile

networks:
  physiomobile:


volumes:
  dbdata:
